language: php

php:
    - 7.2
    - 7.4

matrix:
    fast_finish: true

    include:
        -   php: 7.2
            env: PREFER_LOWEST=1

env:
    global:
        - APPLICATION_ENV=development
        - APPLICATION_STORE=DE

before_install:
    - phpenv config-rm xdebug.ini
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - php composer.phar selfupdate --2

install:
    - COMPOSER_MEMORY_LIMIT=-1 php composer.phar install --prefer-dist --no-interaction
    - if [[ $PREFER_LOWEST == 1 ]]; then COMPOSER_MEMORY_LIMIT=-1 php composer.phar update --prefer-lowest --prefer-stable --prefer-dist --no-interaction ; fi
    - if [[ $PREFER_LOWEST == 1 ]]; then COMPOSER_MEMORY_LIMIT=-1 php composer.phar require --dev dereuromark/composer-prefer-lowest; fi

script:
    - find ./src -path src -prune -o -type f -name '*.php' -print0 | xargs -0 -n1 -P4 php -l -n | (! grep -v "No syntax errors detected" )
    - composer cs-check

    - if [[ $PREFER_LOWEST == 1 ]]; then vendor/bin/validate-prefer-lowest || true; fi

cache:
    directories:
        - $HOME/.composer/cache/

notifications:
    email: false
